name: Deploy Services

on:
  push:
    branches:
      - 'main'
    paths:
      - 'service-config.json'

jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI ğŸ—ï¸
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false

      - name: Setup Node ğŸ—ï¸
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      - name: Install Node Modules ğŸ”§
        run: npm install

      - name: Call Deploy Script ğŸš€
        run: npm run deploy
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
