name: Deploy Services (Test)

on:
  push:
    branches:
      - 'deployed-services/test'
    paths:
      - 'service-config.test.json'

jobs:
  deploy-test:
    name: Deploy (Test)
    runs-on: ubuntu-latest
    environment:
      name: Test
      url: https://web-app.j73b4w218e4.us-south.codeengine.appdomain.cloud

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2
        with:
          ref: 'deployed-services/test'

      - name: Setup IBM Cloud CLI â›…
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud config --check-version false
          ibmcloud plugin install code-engine
          ibmcloud login --apikey ${{ secrets.CODE_ENGINE_API_KEY }} -r 'us-south'

      - name: Setup Node ğŸ—
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Micromanage ğŸ”§
        run: npm install micromanage-cli

      - name: Call Deploy Script ğŸš€
        run: npx micromanage service deploy --target=test
        env:
          CONTAINER_REGISTRY: us.icr.io
          CONTAINER_REGISTRY_NAMESPACE: carbon-platform
          CODE_ENGINE_PROJECT: carbon-platform-test
