name: Deploy Production Services

on:
  push:
    branches:
      - 'main'
    paths:
      - 'service-config.prod.json'

jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2

      # TODO: Require 2 reviews for prod deploys

      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI üèóÔ∏è
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false

      - name: Setup Node üèóÔ∏è
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      - name: Install Node Modules üîß
        run: npm install

      - name: Call Deploy Script üöÄ
        run: npm run deploy --target=prod
        env:
          IBM_CLOUD_API: https://cloud.ibm.com
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          CLOUD_FOUNDRY_ORGANIZATION: ${{ secrets.CLOUD_FOUNDRY_ORGANIZATION }}
          CLOUD_FOUNDRY_SPACE_PREFIX: ${{ secrets.CLOUD_FOUNDRY_SPACE_PREFIX }}
          CLOUD_FOUNDRY_REGION: ${{ secrets.CLOUD_FOUNDRY_REGION }}
