name: Deploy Test Services

on:
  push:
    branches:
      - 'deployed-services/test'
    paths:
      - 'service-config.test.json'

jobs:
  build-and-deploy:
    name: Build And Deploy (Test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2
        with:
          ref: 'deployed-services/test'

      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI ğŸ—
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install code-engine
      - name: Login to IBM Cloud â›…
        run: ibmcloud login --apikey ${{ secrets.CODE_ENGINE_API_KEY }}

      - name: Setup Node ğŸ—
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node Modules ğŸ”§
        run: npm install @carbon-platform/micromanage-cli

      - name: Call Deploy Script ğŸš€
        run: npx micromanage deploy --target=test
        env:
          CONTAINER_REGISTRY_SERVER: us.icr.io
          CONTAINER_REGISTRY_NAMESPACE: carbon-platform-test
          CODE_ENGINE_PROJECT: carbon-platform-test
