name: Nightly Version

on:
  schedule:
    #       â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ minute (0 - 59)
    #       â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ hour (0 - 23)
    #       â”‚ â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ day of the month (1 - 31)
    #       â”‚ â”‚ â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ month (1 - 12 or JAN-DEC)
    #       â”‚ â”‚ â”‚ â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ day of the week (0 - 6 or SUN-SAT)
    #       â”‚ â”‚ â”‚ â”‚ â”‚
    #       â”‚ â”‚ â”‚ â”‚ â”‚
    #       â”‚ â”‚ â”‚ â”‚ â”‚
    - cron: 0 4 * * *

  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  nightly-version:
    name: Nightly Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.JOE_GITHUB_TOKEN }}
      
      - name: Set up Git User ğŸ¤–
        run: |
          git config --global user.email "jdharvey@us.ibm.com"
          git config --global user.name "Joe Harvey"

      - name: Setup Node ğŸ—ï¸
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node Modules ğŸ”§
        run: npm ci

      - name: Version ğŸš€
        run: npm run version
